stages:
  - build
  - deploy

variables:
  NEXUS_REGISTRY: "***REMOVED***:8123"
  NEXUS_IMAGE_TAG: $NEXUS_REGISTRY/crs:latest
  URL_DEPLOY_CRS: "http://***REMOVED***:19000/api/v2/job_templates/36/launch/"

build-npm:
  stage: build
  image: node:lts
  script:
    - npm ci
    - npm run build
    - npm publish
  
  rules:
    - if: $CI_COMMIT_TAG != null

build-docker:
  stage: build
  image:
    name: docker:19.03.13
  services:
      - name: docker:19.03.13-dind
        entrypoint: ["sh", "-c", "dockerd-entrypoint.sh --insecure-registry=$NEXUS_REGISTRY"]
  before_script:
    - docker login $NEXUS_REGISTRY -u $NEXUS_USER -p $NEXUS_PASSWORD
  script:
    - docker build -t $NEXUS_IMAGE_TAG .
    - docker push $NEXUS_IMAGE_TAG
  after_script:
    - docker logout $NEXUS_REGISTRY
  rules:
    - if: $CI_COMMIT_TAG != null

deploy:
  stage: deploy
  script:
    - 'curl --request POST --header "Authorization: Bearer $ANSIBLE_DEPLOY_TOKEN" "$URL_DEPLOY_CRS"'
  rules:
    - if: $CI_COMMIT_TAG != null
    
