openapi: '3.0.2'
info:
  title: ''
  version: ''

paths:
  /_IGNORE_PATH:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    CompactJWS:
      title: CompactJWS
      type: string
      pattern: '^[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$'
