openapi: '3.0.2'
info:
  title: ''
  version: ''

paths:
  /_IGNORE_PATH:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    SignedResolution:
      title: SignedResolution
      type: object
      required:
        - signedResolution
      properties:
        signedResolution:
          $ref: "./compact-jws.yaml#/components/schemas/CompactJWS"
          description: |
            A signed resolution object as a compact JWS signed by the CRS. The payload of a resolution is:
            
            ```typescript
            {
              type: 'verification' | 'dispute'
              dataExchangeId: string // the unique id of this data exchange
              resolution: 'completed' | 'not completed' | 'accepted' | 'denied' // whether the data exchange has been verified to be complete ('completed' | 'not completed') or if a dispute has been 'accpeted' (valid claim) or 'denied'.
              iat: nume // unix timestamp stating when it was verified
              iss: string // the public key of the CRS in JWK
            }
            ```
            