openapi: '3.0.2'

info:
  version: ''
  title: ''

paths:
  /verification:
    post:
      tags:
        - Protected
      summary: verification request of completness of non-repudiation protocol regarding a data exchange
      operationId: verification
      x-eov-operation-handler: routes/verification
      requestBody:
        description: initiates a verification
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerificationInput"
      responses:
        "200":
          description: the ID and type of the created account
          content:
            application/json:
              schema:
                $ref: "../schema/signed-resolution.yaml#/components/schemas/SignedResolution"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../schema/error.yaml#/components/schemas/ApiError"

components:
  schemas:
    VerificationInput:
      title: VerificationInput
      description: |
        Expected input is a verification request as a compact JSON Web Signature (JWS) along with the public key to verify it. For the request to be accepted, it MUST be signed with the same key it was used during the data exchange for this verification.
      type: object
      required:
        - verificationRequest
        - publicJwk
      properties:
        verificationRequest:
          $ref: "../schema/compact-jws.yaml#/components/schemas/CompactJWS"
        publicJwk:
          type: string
        